config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  resources :posts do
    resources :comments
  end
  
  resources :posts do
    resources :likes, only: :create 
    delete "like" => "likes#destroy"
  end

  resources :users, only: %i[index update]
  resources :friends 
  
  get "users" => "users#index"
  get "search" => "users#search"
  
  post "create_comment/:id" => "comment_posts#create" , as: "create_comment"

  devise_for :users, controllers: {:registrations => 'users/registrations', :sessions => 'users/sessions'}
  root "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :owner, polymorphic: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login, only: %i[ create destroy]
  before_action :set_post, only: %i[index create destroy]
  before_action :set_comment, only: :destroy
 
  def index
    @comments= @post.comments
    @user= User.find(@post.user_id)

      respond_to do |format|
        format.html
        format.js{render "index", layout: false, content_type: 'text/javascript'}
      end
  end

  def create 
    if @post.comments.create(content: params[:content], owner: current_user)
      ActionCable.server.broadcast "comment",{count_comment: @post.comments.size()}
      @comments= @post.comments
      
      respond_to do |format|
        format.html{redirect_to post_comments_path(@post.id)}
        format.js{render "create", layout: false, content_type: 'text/javascript'}
      end

    else
      flash[:error]="Fail"

      respond_to do |format|
        format.js{render "create", layout: false, content_type: 'text/javascript'}
      end
    end           
  end

  def destroy
    authorize @comment
    
    if @comment.destroy
      ActionCable.server.broadcast "comment",{count_comment: @post.comments.size()}
      redirect_to post_comments_path(@post.id)

    else
      flash[:error]="Comment destroy fails!!"

      ActionCable.server.broadcast "create",{count_comment: @post.comments.size()}    
      redirect_to post_comments_path(@post.id)
    end
  end

  private
  def set_post   
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment= Comment.find(params[:id])
  end

  def require_login
    if !user_signed_in?
      flash[:error]="Log in to add friends, like posts, and create comments!!"
      
      set_post 
      redirect_to post_comments_path(@post.id)
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_index.slim
- @comments.each do |comment|
  .comment_card
    .comment_card__user

      .comment_card__user__ball
        - if comment.owner.avatar.attached? 
          = image_tag comment.owner.avatar 

        - else
          i.bi.bi-person-workspace

      = link_to friend_path(comment.owner), method: :get, class:"link_full_name"
        = @post.name_user_comment(comment.owner_id) 
          
      - if current_user.id == comment.owner_id
        = button_to "X",  post_comment_path(@post.id, comment.id), class:"comment_card-delete", method: :delete, data:{confirm:"Are you sure?"}
      
      .comment_card__content
        = comment.content

app/views/comments/create.js.slim
|
  $('#list-comments').html('#{j render("comments/index", locals: {comments: @comment})}');
  $('.txt_content').val("");

  
 

app/views/comments/destroy.js.slim
|
  $('#list-comments').html('#{j render("comments/index", locals: {comments: @comment})}');
  

app/views/comments/index.js.slim
|
  $('#list-comments').html('#{j render("comments/index", locals: {comments: @comment})}');
  

app/views/comments/index.slim
.container_comments
  - flash.each do |key, value|
    - if key== "error" || key== "alert"
      .alert.alert-danger.alert-dismissible
        button.close[type="button" data-dismiss="alert"] x
        
        .alert_value--center
          = value
          
    - elsif key== "success"|| key== "notice" 
      .alert.alert-success.alert-dismissible
        button.close[type="button" data-dismiss="alert"] x
    
        .alert_value--center
          = value
          
  .row 
    .col
      .container_comments__image
        = image_tag @post.image 

        .container_comments__image--center 
          = image_tag @post.image 

    .col
      .container_comments--right
        .container_comments--right__content

          .container_comments--right__content__avatar_image
            - if !@user.avatar.blank?
              = image_tag @user.avatar
            
            - else
              i.bi.bi-person-workspace

          .container_comments--right__content__avatar_name
             = link_to friend_path(@user), method: :get, class: "link_full_name"
                = @post.user.full_name
          
          .container_comments--right__content__add_friend 
            = button_to "View profile", friend_path(@user), method: :get, class: "button--red"

        .container_comments__content
          = @post.content

        .container_comments--right__count 
          
          .container_comments--right__count--ball
            - like_exit= Like.exists?(user_id: current_user.id, post_id: @post.id)

            - if like_exit
              = link_to '<i class= "bi bi-hand-thumbs-up-fill" style= "color: #fe2c55;"></i>'.html_safe, post_like_path(@post.id), method: :delete, remote: true, class: "link--black"
            
            - else
              = link_to '<i class= "bi bi-hand-thumbs-up-fill" style= "color: #000000;"></i>'.html_safe, post_likes_path(@post.id), method: :post, remote: true, class: "link--black"
              
          lable 
            = @post.likes.size

          .container_comments--right__count--ball
            i.bi.bi-chat-left-quote-fill

          lable[id= "count-comment_#{@post.id}"]
            = @post.comments.size

        .container_comments--right__comment
          #list-comments
            == render "comments/index", locals: {comments: @comment}
      
        .container_comments--right__create_content
          = form_with model: @comment, local: false, method: :post do |form|

            = form.text_field :content, placeholder: "Add comment",class: "txt_content"
            = form.submit "Post",id: "btn-create-comment", class: "btn_post"
 