config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  resources :posts do
    resources :comments
  end
  
  resources :posts do
    resources :likes, only: :create 
    delete "like" => "likes#destroy"
  end

  resources :users, only: %i[index update]
  resources :friends 
  
  get "users" => "users#index"
  get "search" => "users#search"
  
  post "create_comment/:id" => "comment_posts#create" , as: "create_comment"

  devise_for :users, controllers: {:registrations => 'users/registrations', :sessions => 'users/sessions'}
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments , as: :commentable, dependent: :destroy

  belongs_to :user 

  def name_user_comment(user_id)
    user= User.find(user_id)
    user.full_name
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include Pundit
  
  before_action :require_login, only: %i[ edit update destroy  ]
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    posts = Post.all
    @pagy, @posts= pagy(posts.order(created_at: :desc), items: 5, link_extra: 'data-remote="true"')
    @post= Post.new
  
    respond_to do |format|
      format.html
      format.js { render 'index', layout: false, content_type: 'text/javascript' }
    end 
  end

  def edit
  end

  def create
    @post= Post.new(post_params.merge(user_id: current_user.id))
    
    if @post.save
      flash[:success] = "Post was successfully created!!"
      redirect_to posts_path
      
    else
      flash[:success] = "Post was successfully created!!"
      redirect_to posts_path
    end
  end

  def update
    authorize @post

    if @post.update(post_params)
      redirect_to posts_path
    else
      redirect_to edit_post_path(@post)
    end
  end

  def destroy
    authorize @post
    
    @post.destroy
    flash[:success] = "Post was successfully destroyed!!"
    redirect_to posts_path
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :image)
  end

  def require_login
    if !user_signed_in?
      redirect_to new_user_session_path
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_next_post.slim
.next_link
  == pagy_next_link(@pagy)

app/views/posts/_post.slim
- @posts.each do |post|
  - user= post.user
  .container_posts
    .row
      .col-md-4
        .container_posts__information_user
          .container_posts__information_user__avatar 
            - if !user.avatar.blank?    
              = image_tag user.avatar

          .container_posts__information_user__name
            p = user.full_name

            label
              = post.content

      .col-md-6
        .container_posts__btn_detail--right
          - if user_signed_in?
            - friend= Friend.exist_friends(current_user.id, user.id).first

            - if friend
              - if friend.status =="friend"
                = button_to " Unfollow", friend_path(current_user), method: :delete, class: "button--red", data:{confirm: "Are you sure delete request?"}
              - else
                = button_to " Delete request", friend_path(user), method: :delete, class: "button--red", data:{confirm: "Are you sure delete request?"}
            
            -elsif current_user.id == user.id
              = link_to "<i class= 'bi bi-three-dots-vertical'></i>".html_safe, edit_post_path(post), method: :get
            
            - else
              = button_to "Follow", friends_path(user), method: :post, class: "button--red"

          - else 
            = button_to "Follow", new_user_session_path, method: :get, class: "button--red"
          
    .row
      .col-md-7
        - if post.image.persisted? 

          .container_posts__image
            = image_tag post.image

        .container_posts__create_comment
          = form_with url:"/create_comment/#{post.id}", local: true, method: :post do |form|

            = form.text_field :content, placeholder: "Add comment", class: "txt_comment"
            = form.submit "Post",id: "btn-create-comment", class: "btn_post btn btn-light"
          .create_comment_post[id= "create_comment_post_#{post.id}"]
            
      .col-md-4
        .container_posts__navbar
          .container_posts__navbar__icon
            - if !user_signed_in?
              = link_to '<i class= "bi bi-hand-thumbs-up-fill"></i>'.html_safe, new_user_session_path , method: :get, class: "link--black"
              .container_posts__navbar__icon__count
                label
                  = post.likes.size
                
            - else      
              - if !Like.user_like_exist(post.id, current_user.id).blank?       
                .like_icon[id= "like-icon_#{post.id}"]
                  = link_to '<i class= "bi bi-hand-thumbs-up-fill " style= "color: #fe2c55;" ></i>'.html_safe, post_like_path(post.id), method: :delete, remote: true, class: "link--black"
                   

                .container_posts__navbar__icon__count
                  label[id= "post_#{post.id}"]             
                    = post.likes.size

              - else 
                .like_icon[id= "like-icon_#{post.id}"]
                  = link_to '<i class= "bi bi-hand-thumbs-up-fill " ></i>'.html_safe, post_likes_path(post.id), method: :post, remote: true, class: "link--black"
                
                .container_posts__navbar__icon__count               
                  label[id= "post_#{post.id}"] 
                    = post.likes.size

          .container_posts__navbar__icon
            - if user_signed_in?
              = link_to '<i class= "bi bi-chat-left-quote-fill"></i>'.html_safe, post_comments_path(post.id)
            
            - else
              = link_to '<i class= "bi bi-chat-left-quote-fill"></i>'.html_safe, new_user_session_path
              
            .container_posts__navbar__icon__count
              label[id= "post-comment_#{post.id}"] 
                = post.comments.size
#footer 
      


          
                   

app/views/posts/edit.slim
.container 
  .modal_create_post

    = simple_form_for @post, url: post_path(@post), method: :put do |f|
      .modal_create_post__header
        h3 Detail posts 
      .modal_create_post__center
        p Caption:
        = f.text_area :content, class: "txt_content", placeholder: "Write content..."
        
        .modal_create_post__center__imagebox   
          - if @post.image.persisted?
            #post-img-review.img-review 
              = image_tag @post.image

        - if current_user.id == @post.user_id
        .modal_create_post__body__btn_loadfile
          label for="post_image"                
            = f.file_field :image, id: "post_image", accept: "image/*", class: "input_image"
            | Choose image ...

      .modal_create_post__bottom 
        - if current_user.id == @post.user_id
          = f.submit "Update", class: "btn btn-primary"

          p
          = link_to 'Back |', posts_path 
          = link_to '| Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }   

app/views/posts/index.js.slim
|  
  $('.infinity-scroll-target').append("#{j render(partial: 'post', locals: { posts: @posts }) }");
  $("#next_link").html("#{j render(partial: 'next_post')}")
  

app/views/posts/index.slim
.container
  #container--scroll
    .infinity-scroll-target 
      == render 'posts/post' ,locals: { posts: @posts }

      #footer
  #next_link.d-flex.justify-content-center.pagination-link
    == render partial: "posts/next_post"
  
  